branch-defaults:
  master:
    environment: elastic-beanstalk-app-environment
environment-defaults:
  elastic-beanstalk-app-environment:
    branch: null
    repository: null
global:
  application_name: elastic-beanstalk-app-application
  default_ec2_keyname: null
  default_platform: Node.js 24 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
