name: Deploy to Elastic Beanstalk

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v4
        id: aws_credentials
        with:
          role-to-assume: arn:aws:iam::078050425310:role/github-actions
          aws-region: us-east-1
          output-credentials: true
      - run: aws sts get-caller-identity

      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci
        env:
          NODE_ENV: production

      - run: zip -r deploy.zip . -x "*.git*" "main.tf" "terraform.tfstate*"

      - uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ steps.aws_credentials.outputs.aws-access-key-id }}
          aws_secret_key: ${{ steps.aws_credentials.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.aws_credentials.outputs.aws-session-token }}
          application_name: elastic-beanstalk-app-application
          environment_name: elastic-beanstalk-app-environment
          version_label: ${{ github.ref_name }}-${{ github.run_id }}
          region: us-east-1
          deployment_package: deploy.zip
