name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: aws-actions/configure-aws-credentials@v4
        id: aws_credentials
        with:
          role-to-assume: arn:aws:iam::078050425310:role/github-actions
          aws-region: us-east-1
          output-credentials: true
      - run: aws sts get-caller-identity

      - run: gh release download ${{ github.ref_name }} -p deploy.zip
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ steps.aws_credentials.outputs.aws-access-key-id }}
          aws_secret_key: ${{ steps.aws_credentials.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.aws_credentials.outputs.aws-session-token }}
          application_name: elastic-beanstalk-app-application
          environment_name: elastic-beanstalk-app-environment
          version_label: ${{ github.ref_name }}-${{ github.run_id }}
          region: us-east-1
          deployment_package: deploy.zip
