name: Master Branch Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: npm ci
        env:
          NODE_ENV: production

      - run: zip -r deploy.zip . -x "*.git*" "main.tf" "terraform"

      - uses: actions/upload-artifact@v6
        with:
          name: deploy-artifact
          path: deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: master
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@v7
        with:
          name: deploy-artifact

      - uses: aws-actions/configure-aws-credentials@v4
        id: aws_credentials
        with:
          role-to-assume: arn:aws:iam::078050425310:role/elastic-beanstalk-app-github-actions
          aws-region: us-east-1
          output-credentials: true

      - uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ steps.aws_credentials.outputs.aws-access-key-id }}
          aws_secret_key: ${{ steps.aws_credentials.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.aws_credentials.outputs.aws-session-token }}
          application_name: elastic-beanstalk-app-application
          environment_name: elastic-beanstalk-app-master-env
          version_label: master-${{ github.run_id }}
          region: us-east-1
          deployment_package: deploy.zip
